/*Copyright (c) 2016-2017 jjrichards.com.au All Rights Reserved.
 This software is the confidential and proprietary information of jjrichards.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with jjrichards.com.au*/

package com.smsinternal.sms;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * DocumentHeadersId generated by hbm2java
 */
@Embeddable
public class DocumentHeadersId  implements java.io.Serializable {

    
    private Integer id;
    
    private String columnName;
    
    private String headerInfo;
    
    private String tableName;

    public DocumentHeadersId() {
    }


    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getColumnName() {
        return this.columnName;
    }
    
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }
    public String getHeaderInfo() {
        return this.headerInfo;
    }
    
    public void setHeaderInfo(String headerInfo) {
        this.headerInfo = headerInfo;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof DocumentHeadersId) )
		    return false;

		 DocumentHeadersId that = (DocumentHeadersId) o;

         return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) )
 && ( (this.getColumnName()==that.getColumnName()) || ( this.getColumnName()!=null && that.getColumnName()!=null && this.getColumnName().equals(that.getColumnName()) ) )
 && ( (this.getHeaderInfo()==that.getHeaderInfo()) || ( this.getHeaderInfo()!=null && that.getHeaderInfo()!=null && this.getHeaderInfo().equals(that.getHeaderInfo()) ) )
 && ( (this.getTableName()==that.getTableName()) || ( this.getTableName()!=null && that.getTableName()!=null && this.getTableName().equals(that.getTableName()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getColumnName() == null ? 0 : this.getColumnName().hashCode() );
         result = 37 * result + ( getHeaderInfo() == null ? 0 : this.getHeaderInfo().hashCode() );
         result = 37 * result + ( getTableName() == null ? 0 : this.getTableName().hashCode() );

         return result;
    }


}

