/*Copyright (c) 2016-2017 jjrichards.com.au All Rights Reserved.
 This software is the confidential and proprietary information of jjrichards.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with jjrichards.com.au*/

package com.smsinternal.sms;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * ServiceTypes generated by hbm2java
 */
@Entity
@Table(name="`ServiceTypes`"
    ,schema="dbo"
)

public class ServiceTypes  implements java.io.Serializable {

    
    private Integer id;
    
    private String supplierServiceType;
    
    private String description;
    
    private Boolean professionalIndemnity;
    
    private Boolean publicLiability;
    
    private Boolean workersComp;
    
    private Boolean vehicleInsurance;
    
    private Boolean licenceDeclaration;
    
    private Boolean tradeLicence;
    
    private Boolean licencesAndApprovalsToOperate;
    
    private Boolean ra_jsea;
    
    private Boolean accreditaionCertification;
    
    private Boolean additionalInfo;
    
    private Set<SupplierServices> supplierServiceses = new HashSet<SupplierServices>(0);

    public ServiceTypes() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`ID`", precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`SupplierServiceType`")
    public String getSupplierServiceType() {
        return this.supplierServiceType;
    }
    
    public void setSupplierServiceType(String supplierServiceType) {
        this.supplierServiceType = supplierServiceType;
    }

    

    @Column(name="`Description`")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    

    @Column(name="`ProfessionalIndemnity`")
    public Boolean getProfessionalIndemnity() {
        return this.professionalIndemnity;
    }
    
    public void setProfessionalIndemnity(Boolean professionalIndemnity) {
        this.professionalIndemnity = professionalIndemnity;
    }

    

    @Column(name="`PublicLiability`")
    public Boolean getPublicLiability() {
        return this.publicLiability;
    }
    
    public void setPublicLiability(Boolean publicLiability) {
        this.publicLiability = publicLiability;
    }

    

    @Column(name="`WorkersComp`")
    public Boolean getWorkersComp() {
        return this.workersComp;
    }
    
    public void setWorkersComp(Boolean workersComp) {
        this.workersComp = workersComp;
    }

    

    @Column(name="`VehicleInsurance`")
    public Boolean getVehicleInsurance() {
        return this.vehicleInsurance;
    }
    
    public void setVehicleInsurance(Boolean vehicleInsurance) {
        this.vehicleInsurance = vehicleInsurance;
    }

    

    @Column(name="`LicenceDeclaration`")
    public Boolean getLicenceDeclaration() {
        return this.licenceDeclaration;
    }
    
    public void setLicenceDeclaration(Boolean licenceDeclaration) {
        this.licenceDeclaration = licenceDeclaration;
    }

    

    @Column(name="`TradeLicence`")
    public Boolean getTradeLicence() {
        return this.tradeLicence;
    }
    
    public void setTradeLicence(Boolean tradeLicence) {
        this.tradeLicence = tradeLicence;
    }

    

    @Column(name="`LicencesAndApprovalsToOperate`")
    public Boolean getLicencesAndApprovalsToOperate() {
        return this.licencesAndApprovalsToOperate;
    }
    
    public void setLicencesAndApprovalsToOperate(Boolean licencesAndApprovalsToOperate) {
        this.licencesAndApprovalsToOperate = licencesAndApprovalsToOperate;
    }

    

    @Column(name="`RA/JSEA`")
    public Boolean getRa_jsea() {
        return this.ra_jsea;
    }
    
    public void setRa_jsea(Boolean ra_jsea) {
        this.ra_jsea = ra_jsea;
    }

    

    @Column(name="`AccreditaionCertification`")
    public Boolean getAccreditaionCertification() {
        return this.accreditaionCertification;
    }
    
    public void setAccreditaionCertification(Boolean accreditaionCertification) {
        this.accreditaionCertification = accreditaionCertification;
    }

    

    @Column(name="`AdditionalInfo`")
    public Boolean getAdditionalInfo() {
        return this.additionalInfo;
    }
    
    public void setAdditionalInfo(Boolean additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="serviceTypes")
    public Set<SupplierServices> getSupplierServiceses() {
        return this.supplierServiceses;
    }
    
    public void setSupplierServiceses(Set<SupplierServices> supplierServiceses) {
        this.supplierServiceses = supplierServiceses;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof ServiceTypes) )
		    return false;

		 ServiceTypes that = (ServiceTypes) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

