/*Copyright (c) 2016-2017 jjrichards.com.au All Rights Reserved.
 This software is the confidential and proprietary information of jjrichards.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with jjrichards.com.au*/

package com.smsinternal.sms;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Suppliers generated by hbm2java
 */
@Entity
@Table(name="`Suppliers`"
    ,schema="dbo"
)

public class Suppliers  implements java.io.Serializable {

    
    private Integer id;
    
    private String abn;
    
    private String supplierName;
    
    private String vendorNo;
    
    private Set<MontorVehicleInsurance> montorVehicleInsurances = new HashSet<MontorVehicleInsurance>(0);
    
    private Set<WorkersCompensation> workersCompensations = new HashSet<WorkersCompensation>(0);
    
    private Set<TradeCertificate> tradeCertificates = new HashSet<TradeCertificate>(0);
    
    private Set<SupplierStates> supplierStateses = new HashSet<SupplierStates>(0);
    
    private Set<PublicLiability> publicLiabilities = new HashSet<PublicLiability>(0);
    
    private Set<SupplierServices> supplierServiceses = new HashSet<SupplierServices>(0);
    
    private Status status;

    public Suppliers() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`ID`", precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`ABN`")
    public String getAbn() {
        return this.abn;
    }
    
    public void setAbn(String abn) {
        this.abn = abn;
    }

    

    @Column(name="`SupplierName`")
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    

    @Column(name="`VendorNo`")
    public String getVendorNo() {
        return this.vendorNo;
    }
    
    public void setVendorNo(String vendorNo) {
        this.vendorNo = vendorNo;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="suppliers")
    public Set<MontorVehicleInsurance> getMontorVehicleInsurances() {
        return this.montorVehicleInsurances;
    }
    
    public void setMontorVehicleInsurances(Set<MontorVehicleInsurance> montorVehicleInsurances) {
        this.montorVehicleInsurances = montorVehicleInsurances;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="suppliers")
    public Set<WorkersCompensation> getWorkersCompensations() {
        return this.workersCompensations;
    }
    
    public void setWorkersCompensations(Set<WorkersCompensation> workersCompensations) {
        this.workersCompensations = workersCompensations;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="suppliers")
    public Set<TradeCertificate> getTradeCertificates() {
        return this.tradeCertificates;
    }
    
    public void setTradeCertificates(Set<TradeCertificate> tradeCertificates) {
        this.tradeCertificates = tradeCertificates;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="suppliers")
    public Set<SupplierStates> getSupplierStateses() {
        return this.supplierStateses;
    }
    
    public void setSupplierStateses(Set<SupplierStates> supplierStateses) {
        this.supplierStateses = supplierStateses;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="suppliers")
    public Set<PublicLiability> getPublicLiabilities() {
        return this.publicLiabilities;
    }
    
    public void setPublicLiabilities(Set<PublicLiability> publicLiabilities) {
        this.publicLiabilities = publicLiabilities;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="suppliers")
    public Set<SupplierServices> getSupplierServiceses() {
        return this.supplierServiceses;
    }
    
    public void setSupplierServiceses(Set<SupplierServices> supplierServiceses) {
        this.supplierServiceses = supplierServiceses;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`StatusID`")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Suppliers) )
		    return false;

		 Suppliers that = (Suppliers) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

