/*Copyright (c) 2016-2017 jjrichards.com.au All Rights Reserved.
 This software is the confidential and proprietary information of jjrichards.com.au You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with jjrichards.com.au*/

package com.smsinternal.sms;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * SupplierStatesId generated by hbm2java
 */
@Embeddable
public class SupplierStatesId  implements java.io.Serializable {

    
    private Integer id;
    
    private Integer supplierId;
    
    private Integer statesId;

    public SupplierStatesId() {
    }


    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
    public Integer getStatesId() {
        return this.statesId;
    }
    
    public void setStatesId(Integer statesId) {
        this.statesId = statesId;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof SupplierStatesId) )
		    return false;

		 SupplierStatesId that = (SupplierStatesId) o;

         return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) )
 && ( (this.getSupplierId()==that.getSupplierId()) || ( this.getSupplierId()!=null && that.getSupplierId()!=null && this.getSupplierId().equals(that.getSupplierId()) ) )
 && ( (this.getStatesId()==that.getStatesId()) || ( this.getStatesId()!=null && that.getStatesId()!=null && this.getStatesId().equals(that.getStatesId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getSupplierId() == null ? 0 : this.getSupplierId().hashCode() );
         result = 37 * result + ( getStatesId() == null ? 0 : this.getStatesId().hashCode() );

         return result;
    }


}

